### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by shanghai-Jerry** [facebookresearch/PyTorch-BigGraph#103]
## Steps to reproduce

  1. pip install torchbiggraph
  2. _____
  3. _____

## Observed Results

  * File "/tmp/pip-install-oTIeBd/torchbiggraph/setup.py", line 14, in <module>
        with open("requirements.txt", "rt") as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

## Expected Results

  install success

## Relevant Code

  ```
   No
  ```

**Comment by lerks** [comment]
I've been able to replicate it by calling `pip install torchbiggraph --no-binary ':all:'`, which installs from the .tar.gz. However, by default, my pip installs the .whl which works just fine. While this is certainly a bug we need to fix, I am wondering why your pip chose the .tar.gz. What system are you installing it on?

To unblock you, you could try checkout out the repo (`git clone https://github.com/facebookresearch/PyTorch-BigGraph.git`) then, if you want, check out the v1.dev1 version, the same we have on PyPI (`git checkout v1.dev1`) and then run `pip install .` from inside the repo.

**Comment by shanghai-Jerry** [comment]
I've tried to install it by default way which is actually running  installation  with .whl, but with poor network, fails for many times. So I chose to install from the .tar.gz then I found this problem but not the only one. I also found there is an empty dir `third-party`.

**Comment by lerks** [comment]
Now that you posted the full error message I see that the problem is that you are running Python 2.7, which we don't support. You need to use at least Python 3.6. If you do that you should be able to download and install the wheel.

Anyway, I'm glad that in the end you managed to install it successfully.

Also, `third-party` is how we originally called `torch_extensions`, but it's odd that the directory is still lying around, I'll double check that too...
