### ISSUE TITLE
Regarding output model's predictions 

### ISSUE THREAD

**Issue by HamletMedina** [facebookresearch/PyTorch-BigGraph#112]
Hi, 

First of all. Thank you very much for making it an open source project. I have been using it over the last few weeks.

On my side, I would like to ask you a question. I like the fact that you provide very useful command line utilities for model evaluation as well as for extracting embedding information. My question is,  do you have a similar command utility for saving model’s predictions during the evaluation phase?, I mean, the actual link’s probabilities before computing aggregates measures like auc, Hits@10, etc. . 

I ask you about this because I am studying the case of using predicted link’s probabilities in the evaluation set for a downstream machine learning task. 
 
If this is not the case, given that you know the code very well, could you provide me with some hints about the best place in your code where I could access model’s output in order to do it myself? 
 
Looking forward to your reply.

Thanks in advance

**Comment by lerks** [comment]
The evaluation script is designed to be used in partnership with the train script, in order to measure the quality of the embeddings when optimizing the hyperparameters. As such, it is focuses on providing high level aggregate statistical measures. It's not its goal to be a generic inference tool, i.e., to calculate and return individual predictions.

We don't currently intend to provide such a tool because we feel there are so many ways people would use it that it's impossible to build one solution that satisfies all of them. Therefore, instead, in our documentation we provide a few snippets that implement some basic common cases that users can refer to when implementing their own custom tool. For your use case, I believe you can take a look at this code: https://torchbiggraph.readthedocs.io/en/latest/downstream_tasks.html#predicting-the-score-of-an-edge

**Comment by HamletMedina** [comment]
Hi @lerks , thank you for your reply.
