### ISSUE TITLE
Many to Many Relations 

### ISSUE THREAD

**Issue by makcedward** [facebookresearch/PyTorch-BigGraph#118]
I built multiple cols .tsv file and intent to train multiple relations. Followed #106 suggestions to config "entities" and "relations" in config file. However, there is only 1 value for "rhs" column when using [convert_input_data ](https://github.com/facebookresearch/PyTorch-BigGraph/blob/5e75d706fb0514202f16449eca4cbec61e3397e3/torchbiggraph/converters/import_from_tsv.py#L250)
```
        convert_input_data(
            config.entities,
            config.relations,
            config.entity_path,
            config.edge_paths,
            edge_paths,
            lhs_col=0,
            rhs_col=2, # <----------------only allowing one columns
            rel_col=None
        )
```

How can I handle if I have the following tsv file and relationship? 

Example of tsv file
====
ColA ColB ColC ColD
1 2 3 4
1 2 5 4
1 2 3 3

Actual Relationship
ColA <--> ColB
ColA <--> ColC
ColA <--> ColD
ColC <--> ColD

**Comment by lerks** [comment]
Each line of the TSV file represents _one_ edge, and one edge only has one source and one destination entity. If one of your lines contains information about multiple edges you'll have to split that line into multiple ones, one for each edge.

**Comment by makcedward** [comment]
Thank you @lerks 

So, I need to build the following TSV file
FromNode ToNode
1 2 # refer to data 1
1 3 # refer to data 1
1 4 # refer to data 1
3 4 # refer to data 1
1 2 # refer to data 2, a duplicated relationship is allowed according to the description
1 5 # refer to data 2
1 4 # refer to data 2, a duplicated relationship is allowed according to the description
5 4 # refer to data 2
1 2 # refer to data 3, a duplicated relationship is allowed according to the description
1 3 # refer to data 3
1 3 # refer to data 3, a duplicated relationship is allowed according to the description
3 3 # refer to data 3, it is allowed according to the description

However, what does the following config affect the outcome? How does the model know "2" belongs to ColB entity type while "4" belongs to ColD entity type?
```
"entities": {
    "ColA": {"num_partitions": 1},
    "ColB": {"num_partitions": 1},
    "ColC": {"num_partitions": 1},
    "ColD": {"num_partitions": 1},
},
"relations": [
    {"name": "rel-01", "lhs": "ColA", "rhs": "ColB"},
    {"name": "rel-02", "lhs": "ColA", "rhs": "ColC"},
    {"name": "rel-03", "lhs": "ColA", "rhs": "ColD"}
    {"name": "rel-03", "lhs": "ColC", "rhs": "ColD"}
]
```

**Comment by lerks** [comment]
If your edges can be of different types, you have to add one column on each row of the TSV file to specify the type of the edge. Types are non-negative integers, which correspond to the index of the relation in the `relations` field of the config (thus, your `rel-01` would be type 0, `rel-02` type 1, and so on). Then you specify the index of this new column as the `rel_col` argument to `convert_input_data`.

**Comment by lerks** [comment]
By the way, I saw that the way you converted your original representation to a list of edges caused you to have duplicate edges. This is perfectly fine if it's what you need, but just be aware that you don't have to have duplicates. As for the self-loop, it's not really a self-loop, because it connects two entities, both with ID 3, which however are of different types, therefore they are not the same entity.

**Comment by makcedward** [comment]
@lerks thank you for the quick response. I am able to build correct multi entities format TSV files for training. 

Regarding to `Types are non-negative integers`, I need to output relation's name rather than index as [it ](https://github.com/facebookresearch/PyTorch-BigGraph/blob/5e75d706fb0514202f16449eca4cbec61e3397e3/torchbiggraph/converters/import_from_tsv.py#L74)requires name.
```
1 rel-01 2
1 rel-02 3
```

On the other hand, may I get more elaboration on `duplicate edges` and `self-loop edge`? From [documentation](https://torchbiggraph.readthedocs.io/en/latest/data_model.html), it mentioned `Multiple edges between the same pair of entities are allowed`. My intention to have duplicate edges (actually, it is not duplicate in terms of data) is introducing influence rate (or weight refer to 1 --> 2 relationships). For example, `1-->3` is more frequently than `1-->4` and it is reflecting by those duplicate records. 

For my `self-loop`, ColC and ColD are in the same type but describing different information. For example, ColA is house buyer while ColC and ColD are buyer's agent and seller's agent. It is possible that single-agent represents both buyer and seller sometimes.

**Comment by lerks** [comment]
> I need to output relation's name rather than index as it requires name.

Yes, sorry, I was wrong: in the TSV the relation types can be names, the importer will take care of mapping them to integers. (I updated the post above)

As for how to model your problem as a graph, unfortunately that is part of the design decisions of your pipeline and probably something for which you need to try out different options and compare the results, so I can't directly advise you on what to do. I can tell you some general rules though. First of all, IDs in the TSV are specific to the entity type. If two entities have the same ID but are of different type, they are different entities (i.e., different nodes in the graph, for which we'll learn separate independent embeddings). So, in your case, if you keep ColC and ColD separate types, you can't have the same agent belong to both types. My impression is that you can merge ColC and ColD in a single type called Agent: due to the fact that there are different _edge_ types for Buyer-to-Buyer-Agent and Buyer-to-Seller-Agent (which in your case you called `rel-02` and `rel-03` respectively) the system will be able to distinguish what role each agent is playing for a given edge.

As for giving some edges more weight, you have two options. One option is what you're already doing, namely artificially replicating some edges multiple times in order for them to be counted "more often" than others. Another option, if you want to give all edges of a certain type the same weight, is to use the `weight` option of the relation type config. However, you're saying that "`1 --> 3` is more frequent than `1 -->4 `", so I imagine that each of this relation has a number of occurrences in your original data. So perhaps you should try to just recreate these occurrences exactly in the data, and have PBG figure out how to use them?

**Comment by makcedward** [comment]
Thank you very much for detail explanation and suggestion.

**Comment by lerks** [comment]
No problem! I'm closing this, but feel free to reopen it if you have follow-ups.
