### ISSUE TITLE
Minimum count for entities or relations

### ISSUE THREAD

**Issue by naxu-hiretual** [facebookresearch/PyTorch-BigGraph#123]
If I do not want to learn the embeddings of some low-frequent entities or relations, is there a parameter in config file where I can set a frequency threshold?

**Comment by lerks** [comment]
At training time PBG will learn the embeddings of all entities it knows about, and will use all the edges it has at its disposal. However, during pre-processing, you can remove the low-frequency entities and relation types so that they don't even reach training. If you're using `import_from_tsv`, there are two command-line options to do so: `--entity-min-count` and `--relation-type-min-count`. Is this what you were looking for?

**Comment by naxu-hiretual** [comment]
@lerks Yes, thanks a lot for answering my question.
