### ISSUE TITLE
Convert from tsv to hdf5 format

### ISSUE THREAD

**Issue by joanPlepi** [facebookresearch/PyTorch-BigGraph#125]
The pretrained model provided from you here [https://dl.fbaipublicfiles.com/torchbiggraph/wikidata_translation_v1.tsv.gz](url) is in .tsv format. However, you mention in documentation that tsv format is mainly for small dataset, and the size of that pretrained model after decompressing is around 113GB making it very slow to convert that into a numpy array (as also noted in the documentation)

Is there any way to convert this .tsv file in hdf5 or is there any pre-trained model already in hdf5 format?

**Comment by lerks** [comment]
We provide this dataset also in other formats which are smaller, see the bottom of this page: https://torchbiggraph.readthedocs.io/en/latest/pretrained_embeddings.html#wikidata

However, as you correctly point out, there is no HDF5 version. I don't know if we had a reason for not providing it, but I can't think of any now, so I'll convert the TSV one to HDF5 and upload it there. Stay tuned!

**Comment by lerks** [comment]
While I was doing this I found a few reasons why the HDF5 format is not great for this purpose:
- It represents the entities using only arbitrary IDs (the offsets), rather than the semantically meaningful names used by Wikidata, so one needs a separate mapping between the two (which is something we only recently added to the entity count storage). The same holds for relation types.
- It is designed to hold the embedding tables in partitioned form, as that is useful during training (loading and checkpointing), but irrelevant to downstream tasks (and actually burdensome as they need to handle this extra complexity).
- It has a bunch of features (version number, stats logs, ...) which are meaningful to track training progress but not when distributing embeddings.

Anyways, these are all inconveniences, and not blockers, thus I produced an HDF5-based dump of the Wikidata embeddings, which you can find here: https://dl.fbaipublicfiles.com/torchbiggraph/wikidata_translation_v1.tar.gz

**Comment by rkindi** [comment]
Closing the issue bc the hdf5 dump was made available by @lw
