### ISSUE TITLE
support for other optimization algorithms

### ISSUE THREAD

**Issue by huidongchen** [facebookresearch/PyTorch-BigGraph#135]
Hi,

I noticed that currently in PBG the optimizer (Adagrad) is hard-coded. I'm wondering if there are any plans to support other optimization algorithms. Not sure technically how difficult it is though. (I was looking at the module `row_adagrad`. But it doesn't seem trivial for me to adapt it for other optimizers)

**Comment by asaluja** [comment]
+1. I'd love to have a vanilla SGD implementation here too.

**Comment by adamlerer** [comment]
It is in fact trivial to adapt it for vanilla SGD: simply swap out `torchbiggraph.AsyncAdagrad` and `torchbiggraph.RowAdagrad` for `torch.optim.SGD` everywhere in the code.

Switching to other optimizers is also similarly trivial with two important caveats:
1. Without the optimization of `RowAdagrad`, your memory usage will go up by >=2x to store the optimizer state for optimizers like `Adam`. That may or may not be an issue for you depending on your dataset size.
2. Some optimizers may interact badly with the HOGWILD CPU training, see 
https://github.com/facebookresearch/PyTorch-BigGraph/commit/be2e21a60c1c5b18eeb4c4823854d049e49b3268

If you want to make the optimizer configurable through the config file rather than swapping it out in the code, that would be very simple (just add a parameter in config.py and add a branch where the optimizer is created based on that parameter), but I'm not sure we will accept it upstream because we have not validated other optimizers.
