### ISSUE TITLE
can not install torch

### ISSUE THREAD

**Issue by xiakexing716** [facebookresearch/PyTorch-BigGraph#16]
## Steps to reproduce

  1. pip install torchbiggraph
 
## Observed Results

   Could not find a version that satisfies the requirement torch>=1.0 (from torchbiggraph) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0 (from torchbiggraph)

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by lerks** [comment]
PBG requires a recent release of PyTorch, version 1.0 or newer. It looks like your system only has rather old versions. Without knowing anything else about your setup I cannot really help you out much. The answer might be as simple as just upgrading through `pip`, or it may require using your system's package manager, or asking your administrator. The best resources on how to install and upgrade PyTorch are found on their website: https://pytorch.org/.

As this issue is not about a problem with PBG, I'm closing it.
