### ISSUE TITLE
we want to do evaluation when training, and we will set eval_fraction=0.3(or other value), but what if the sample choose for evaluation not in the training set, how the model do?

### ISSUE THREAD

**Issue by circlegao** [facebookresearch/PyTorch-BigGraph#191]
1、we want to do evaluation when training, and we will set eval_fraction=0.3(or other value), but what if the sample choose for evaluation not in the training set, how the model do?
2、how the model choose sample for evaluation when training?

**Comment by lw** [comment]
For eval-during-training, PBG will remove a certain fraction of edges from its training data and use those to evaluate. Hence you will never evaluate using edges that were in the training set. This is the point of evaluation, or else you'd risk seeing good eval results just because the model memorized the input and thus you wouldn't be able to detect overfit-vs-underfit problems.

**Comment by rkindi** [comment]
Closing issue
