### ISSUE TITLE
Can I add a custom initial embedding to the entity before starting the training? 

### ISSUE THREAD

**Issue by illcat** [facebookresearch/PyTorch-BigGraph#199]
## Steps to reproduce

  1. _____
  2. _____
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results

  * What did you expect to happen?

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by lw** [comment]
You can prepare a directory that contains files in the same format used for checkpointing, with an arbitrary embedding, and set that directory as the `init_path` parameter in your config. In that case PBG will use those embeddings rather than initializing them randomly.

You can find more info here:
https://torchbiggraph.readthedocs.io/en/latest/input_output.html
https://torchbiggraph.readthedocs.io/en/latest/configuration_file.html

**Comment by illcat** [comment]
> You can prepare a directory that contains files in the same format used for checkpointing, with an arbitrary embedding, and set that directory as the `init_path` parameter in your config. In that case PBG will use those embeddings rather than initializing them randomly.
> 
> You can find more info here:
> https://torchbiggraph.readthedocs.io/en/latest/input_output.html
> https://torchbiggraph.readthedocs.io/en/latest/configuration_file.html

@lw Thansk.

However, when I run the **livejournal** example, 
```
    convert_input_data(
        config.entities,
        config.relations,
        config.entity_path,
        config.edge_paths,
        input_edge_paths,
        TSVEdgelistReader(lhs_col=0, rhs_col=1, rel_col=None),
        dynamic_relations=config.dynamic_relations,
    )
```
this code still failed to complete after running for several hours.
Is the efficiency of TSVEdgelistReader so low? Will it make a big improvement if I switch to **parquet**? 

Besides, could you provide an example of **multi-machine distributed training**?

**Comment by illcat** [comment]
@lw Thanks. 
In addition, is there a detailed configuration for multi-machine distributed training?
