### ISSUE TITLE
AttributeError: 'EntityList' object has no attribute 'to_tensor'

### ISSUE THREAD

**Issue by jiehuaou** [facebookresearch/PyTorch-BigGraph#43]
## Steps to reproduce

  1.  pip install torchbiggraph
  2.  python examples/fb15k.py
  3.  show running

## Observed Results

  * 2019-04-30 13:30:43  Exiting
2019-04-30 13:30:43  Building links map from path data/FB15k/freebase_mtr100_mte100-test_partitioned
Traceback (most recent call last):
  File "examples/fb15k.py", line 91, in <module>
    main()
  File "examples/fb15k.py", line 85, in main
    do_eval(eval_config, FilteredRankingEvaluator(eval_config, filter_paths))
  File "/root/graph/PyTorch-BigGraph/examples/filtered_eval.py", line 56, in __init__
    cur_lhs = lhs.to_tensor()[i].item()
AttributeError: 'EntityList' object has no attribute 'to_tensor'

## Expected Results

  * should show it is finished successfully.

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by lerks** [comment]
Thanks for bringing this to our attention! The issue is that a recent commit (https://github.com/facebookresearch/PyTorch-BigGraph/commit/6bb57646c93a5cd78563f5fe57f3429147c472ea) changed some internal interfaces and if one runs the `fb15k.py` script from the master branch with the latest version we released on pip there's now an incompatibility.

In the short term, I can probably fix it by releasing a new version (say, 1.dev1). In the long term (say, after we release a stable version 1 and start working on version 2 which may break some interfaces) we should either bundle the `fb15k.py` script in the pip distribution, or instruct users to check out the v1 branch when running `fb15k.py`, or tell users to install the unstable v2 branch. I'll need to think about what approach is best...

**Comment by lerks** [comment]
I've released v1.dev1. If you install it with pip you will now have access to a command, `torchbiggraph_example_fb15k`, which runs the example script using compatible versions of the script  and of the library. This means it is not necessary to clone the repository anymore.
