### ISSUE TITLE
Feature Request: Allow configuration without config file

### ISSUE THREAD

**Issue by simonepri** [facebookresearch/PyTorch-BigGraph#50]
Right now the [`convert_input_data`](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/converters/import_from_tsv.py#L226) and [`parse_config` ](https://github.com/facebookresearch/PyTorch-BigGraph/blob/master/torchbiggraph/config.py#L434) are coded in such a way that one's **have to** pass the name of a config file to call them.

It would be nice to have two other functions that allow us to directly provide a dictionary instead.

I'm happy to contribute in case there's interest.

**Comment by lerks** [comment]
I'm not sure what you're trying to achieve, so I'm not sure what exactly you're looking for.

Our command line interface does indeed take the path of a Python file and then loads it and calls a function in it to retrieve a dictionary, which is parsed. We to have a Python file with code rather than, say, a JSON file with just data so that one could customize the config file based for example on the environment variables. Also, I believe due to a limitation of Python's import mechanics, we need to have a real path for that file, and cannot just get the source code on the standard input.

However, after the dictionary has been retrieved from that file, that file isn't needed anymore. So if you want to get the config from somewhere else you can inject your config at this stage. There are several ways you could do that. The "cleanest" one, IMO, is to do what we do in our [functional tests]() and instantiate a `ConfigSchema` object, and use it for example as follows:
```
entity_name = "e"
relation_config = RelationSchema(
    name="r", lhs=entity_name, rhs=entity_name)
config = ConfigSchema(
    dimension=10,
    relations=[relation_config],
    entities={entity_name: EntitySchema(num_partitions=1)},
    entity_path="entities",
    edge_paths=["edges"],
    checkpoint_path="checkpoints",
)
train(config, rank=0)
```
If you want to use the same dict-based format that the `get_torchbiggraph_config` function returns (maybe because you want to be able to serialize it) you can produce a `ConfigSchema` object from it as follows:
```
entity_name = "e"
relation_config_dict = {
    "name": "r", "lhs": entity_name, "rhs": entity_name}
config_dict = {
    "dimension": 10,
    "relations": [relation_config],
    "entities": {entity_name: {"num_partitions": 1}},
    "entity_path": "entities",
    "edge_paths": ["edges"],
    "checkpoint_path": "checkpoints",
}
config = ConfigSchema.from_dict(config_dict)
```
This is more "basic" than the default code, so you will miss out on some features, namely the ability to override parameters from the command line, some proper error handling and (until I fix this) the ability to activate verbose logging. Hopefully, however, this will be good enough for what you need.

**Comment by simonepri** [comment]
Thank you for your detailed answer, Luca.

I'll try to clarify with some code what I had in mind.

Let's imagine that I want to use `convert_input_data` programmatically and I don't have a configuration file.

I'd like to be able to do something like this:

```python
config = # config obtained either with parse_config or with ConfigSchema.from_dict 
convert_input_data(
  config, # instead of providing the config file
  #...
 )
```

I also mentioned the `parse_config` function because as you already noticed, it has some logic to activate verbose logging and people may want to have such ability also if they don't have a config file.

**Comment by lerks** [comment]
You are right that what I described above only works for train and eval but it isn't possible for the `import_from_tsv` command, i.e., there is no "lower-level" function that does the same job but takes a config _object_ (rather than a path to a .py file). So, if you want to fix that a pull request would be welcome!

**Comment by simonepri** [comment]
To give you more context, a use case for this would be the in a Jupiter Notebook where it would be awkward to have a config file.

The following is just a simple example of how one may want to use the library programmatically.
```python
import os
import attr

import torchbiggraph.converters.utils as utils
from torchbiggraph.config import ConfigSchema
from torchbiggraph.converters.import_from_tsv import convert_input_data
from torchbiggraph.eval import do_eval
from torchbiggraph.train import train

# Download data
FB15K_URL = 'https://dl.fbaipublicfiles.com/starspace/fb15k.tgz'
FILENAMES = {
    'train': 'FB15k/freebase_mtr100_mte100-train.txt',
    'valid': 'FB15k/freebase_mtr100_mte100-valid.txt',
    'test': 'FB15k/freebase_mtr100_mte100-test.txt',
}

data_dir = 'data'
fpath = utils.download_url(FB15K_URL, data_dir)
utils.extract_tar(fpath)

# Load configs
entity_name = "e"
edge_paths = [os.path.join(data_dir, name) for name in FILENAMES.values()]
config_dict = {
    "dimension": 10,
    "relations": [{"name": "r", "lhs": entity_name, "rhs": entity_name}],
    "entities": {entity_name: {"num_partitions": 1}},
    "entity_path": "entities",
    "edge_paths": edge_paths,
    "checkpoint_path": "checkpoints",
}
config = ConfigSchema.from_dict(config_dict)

# Import data
convert_input_data(
    config, #edge_paths is not needed anymore if we provide the config object
    lhs_col=0,
    rhs_col=2,
    rel_col=1,
)

# Train
train_path = [convert_path(os.path.join(data_dir, FILENAMES['train']))]
train_config = attr.evolve(config, edge_paths=train_path)
train(train_config)

# Eval
eval_path = [convert_path(os.path.join(data_dir, FILENAMES['test']))]
relations = [attr.evolve(r, all_negs=True) for r in config.relations]
eval_config = attr.evolve(config, edge_paths=eval_path, relations=relations)
do_eval(eval_config)
```

**Comment by adamlerer** [comment]
+1

Thanks @simonepri . I agree, all components of PBG should be callable without referencing a config file. If that's not the case it should definitely be fixed.

**Comment by lerks** [comment]
If you feel like taking a shot at fixing it and sending a pull request that would be very welcome. Otherwise I can do it, but I can't guarantee a timeframe for that.
