### ISSUE TITLE
error running torchbiggraph_live_journal

### ISSUE THREAD

**Issue by sckGeek** [facebookresearch/PyTorch-BigGraph#68]
## Steps to reproduce

  1. run the shell script put into /usr/bin/torchbiggraph_live_journal (note that it creates an uncompressed file that script expects to be compressed).
  2. fails in the import_from_tsv.py in generate_edge_path_files
  3. _____

## Observed Results

  * What happened?  This could be a description, log output, etc.

## Expected Results
I am trying to develop an intuition between an entity_type vs an entity_name and how many partitions should be devoted to a given node type (config file just gives an example of 1).
The point of running this is to shard a graph that can't be held in memory and train in parallel on . a multi-core conventional cpu. please advise
  * What did you expect to happen?
I am confused about your terminology I think

## Relevant Code

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by sckGeek** [comment]
see if you can run the livejournal pull data script. I wanted to eyeball the edge files created. I'd like to understand how one should partition/shard the graph , the examples for FB15K just use a single partition

**Comment by lerks** [comment]
I don't understand what issue you are encountering. When you say `torchbiggraph_live_journal` do you mean the `torchbiggraph_example_livejournal` command? I've just tried to run it on my MacBook both from the v1.dev1 version and from master and the pre-processing phase (the one where import_from_tsv.py is used) succeeded. If you're having an issue with that please tell us the exact command you ran and the error and the logs you are getting, otherwise we can't help you.

**Comment by sckGeek** [comment]
my mistake, yes, that was the command but it was a proxy issue my end.
