### ISSUE TITLE
Question: Why is PBG CPU-only?

### ISSUE THREAD

**Issue by simonepri** [facebookresearch/PyTorch-BigGraph#77]

**Comment by lerks** [comment]
We're working to bring it to GPU (one work-in-progress is in the `gpu` branch of my fork).

**Comment by ramithp** [comment]
Could we have an indication (roughly) on progress made so far, and work left on adding GPU support?

**Comment by lerks** [comment]
I can't give an estimate on when this will be ready. We're still in a design and prototype phase. There's some code in the `gpu` branch of my fork, which "works" (it runs and should produce the same embeddings as on CPU) but it's not as performant as we wish it to be.

The "core issue" about using GPUs is that the effective computation is rather small and fast (basically a handful of matrix multiplies) but it requires a disproportionally large amount of memory to be moved around (the embedding tables). GPUs, however, are much faster at computing but can hold less memory than the typical CPU-only setup.

Our current approach to this is to basically reuse, at a lower level, the technique PBG adopts to split up work among the trainers. That is, we treat the GPUs on a single machine in the same way we treat the multiple machines in a network. Just like we partition the entities of the whole graph and in turn bucket its edges, we have each machine sub-partition the entities of the one bucket it's training on and then sub-bucket its edges. You can see it as a nested/hierarchical partitioning. Each GPU will then in turn train on one sub-bucket at a time, in the same way each machine trains on one (full) bucket at a time.

This "works" but it's still far from ideal. There's definitely some "systems" issues stemming from the fact that we're required to do additional data copies (to and from the GPU) that cut into the total training time. However, the "deep" reason this works poorly is that the amount of edges in a (sub-)bucket decreases _quadratically_ in the size of the embedding tables of its (sub-)partitions. What I mean is the following: suppose you have a graph with N entities and M edges. If you were to partition it 10x10 (because each of these 10 partitions fits in your CPU memory), then for each bucket you'd have to load 2*N/10 embeddings and you could process M/(10^2) edges. If however you must sub-partition each bucket again by 10 (thus ending up with a 100x100 sub-partitioning), for each sub-bucket you must load 2*N/100 embeddings but could only process M/(100^2) edges. You will observe that in the first case you can process M/(2*10*N) edges/embedding, whereas in the second case this goes down to M/(2*100*N), i.e., a factor 10 difference. What this means is that the finer you partition the larger the _fraction_ of time you spend moving data around increases w.r.t. the one you spend computing stuff.

Our current ideas to work around this are "technical", i.e., we're trying to optimize our memory usage to squeeze out all we can from our CPU and GPU memory, and we're trying to make data transfers faster (say, by doing asynchronous background copies, direct GPU-to-GPU transfers, ...). Hopefully this will turn out to be enough. But we're not there yet.

**Comment by HenryYihengXu** [comment]
Hi. I tried to add num_gpus=1 in torchbiggraph/examples/configs/fb15k_config.py, but it gives me this error:

**Comment by adamlerer** [comment]
GPU support was just recently added on master (and not yet in the release or pip branch). Have you built from the latest master branch and compiled with `INSTALL_CPP=1` as described in the README?

If you're still having problems, please open another issue so that we can track this issue separately from the CPU-only issue. Thanks!
