### ISSUE TITLE
Is there any reason why PBG can not be used to train word2vec embeddings?

### ISSUE THREAD

**Issue by Santosh-Gupta** [facebookresearch/PyTorch-BigGraph#87]
Sorry for the newbie question, but I have looked up graph embeddings, this repo, and the PBG paper, and it looks like this can be used to train word2vec embeddings (whole other story of why I want to train word2vec on this). I just have to think about it as treating a target word's index as the main node, and the context word's index as the adjacent nodes. 

Or, am I missing something big here?

**Comment by lerks** [comment]
I'm not super familiar with word2vec but from what I understand it should be possible to replicate it using PBG. Have you tried it? Did you run into any issues?

**Comment by Santosh-Gupta** [comment]
Not yet, will try out this week and report back. But word2vec would work something like this, 

Say for a sentence, you have:

"the cat in the hat"

Each of those words has an index, for example

'34 373 23 2 898'

where 34 = the, 373 = cat, 23 = in, etc. 

Each of those indexes corresponds to a vector in an embedding matrix. 

During training, the middle word vector (in this case, the word 'in') would do cos similarity with all the other words in the sentence, and train them to be similar. And then use other random word vectors as negative samples. 

A variation called cbow would take the average of the vectors for the context words (in our case 'the', 'cat', 'the', 'hat') and do cos similarity of the middle word, and that averaged vector. 

I'm not sure about the variation, but it looks like PBG can do the first one, which from my limited knowledge of graph embeddings, is nearly the same thing. A main difference being is that a 'context' for each node will be fixed. ie node 23 will always just have neighbors 34, 373, 2 and 898; since a graph doesn't change. Where as word2vec will have difference context for each node, due to the variety of sentences. 

But as far as I can tell, this won't really matter to PBG.

**Comment by lerks** [comment]
I think there are a couple of point to which one should pay attention.

- Will the same word have different embeddings when it appears as a "target" (i.e., middle word) and when it appears in the context? If so, you need to represent the word as two different nodes, possibly of two different entity types. Otherwise it will be the same entity, of the same type, in both cases.

- Do you care whether the whole context is evaluated at once, at the same time? That is, say the context of "cat" is {"the", "in"}: should the edges ("cat", "the") and ("cat", "in") always necessarily appear in the same batch or can they appear in different batches? In the latter case, you can just mix all the edges coming from all the contexts of all the occurrence of a word in your corpus and then forget where they came from and how they were correlated. If, on the other hand, you need to keep that correlation, then you may want to look into featurized embeddings, which allows you to have edges that go from a word to an entire context (rather than from a word to another word). This however comes with its own set of limitations (e.g., no distributed training).

- Featurized embeddings would also allow you to do the "average over the context" approach you mentioned.

- There is _no_ way in PBG to preserve the order (of edges, of words, of features, ...).

**Comment by Santosh-Gupta** [comment]
> Will the same word have different embeddings when it appears as a "target" (i.e., middle word) and when it appears in the context? If so, you need to represent the word as two different nodes, possibly of two different entity types. Otherwise it will be the same entity, of the same type, in both cases.

I'll definitely have to do that, because in word2vec there are different embeddings for the target words and context words. It can be done without separate embeddings, but somehow the training is much better this way. I think it can be easily done by having the even indexes be the target embedding, and the odd indexes be the context embedding. 

>That is, say the context of "cat" is {"the", "in"}: should the edges ("cat", "the") and ("cat", "in") always necessarily appear in the same batch or can they appear in different batches?

For the first method I explained, skip-gram. They can appear in different batches. As long as the total frequency of the pair in the dataset is the same as the frequency the training. Since there's usually shuffling in word2vec training, they probably wouldn't occur in the same batch often. 

But for the cbow method, where all the context embeddings are averaged, it looks like I'll have to used the featurized embeddings option, it looks like it is described here
https://github.com/facebookresearch/PyTorch-BigGraph/blob/0b2bc4f67786c21afd1abe55077a8d93257396be/docs/source/featurized_entities.rst

**Comment by adamlerer** [comment]
word2vec is (loosely) a linear model that predicts the target word using a bag-of-words on nearby context words. PBG supports this using "featurized entities", but you will have to write some of your own tooling to run in that mode.
word2vec also uses a number of domain-specific tricks that are a bit different from what PBG does (e.g. their specific sampling strategy of words proportional to N^2/3 or whatever), so you probably won't exactly reproduce the word2vec results.
Overall, I would say that PBG is a poor choice to train a word2vec model. There are plenty of good alternatives on the internet. Since you need to use "featurized mode", you won't be able to take advantage of PBG's scaling properties anyway.

**Comment by Santosh-Gupta** [comment]
Well, I'm not training exactly word2vec, but the item embeddings I am training will be trained the same way as word2vec. But the reason I looked into PBG is 'graph partitioning, so that the model does not have to be fully loaded into memory', but it looks like that won't be available with "featurized mode".
