### ISSUE TITLE
How to get random(untrained) model performance?

### ISSUE THREAD

**Issue by mralexisw** [facebookresearch/PyTorch-BigGraph#88]
I am trying to train a few models with PBG and I am wondering how I could get a random baseline of the model. Also, is there any standard/convention on interpreting the performance (e.g. what is a reasonable pos rank/MRR)? 

Thanks!

**Comment by lerks** [comment]
I don't think we currently provide a way of running eval on a purely random embedding table: we do initialize the embeddings randomly during training but we never checkpoint them in this state, so all the checkpoints you can get have already had some training applied to them. You can of course create a "fake" manual checkpoint with random data in it, but we don't provide tools for that...

It should however be possible to estimate what a random MRR could look like. If all the embeddings are random and independent, the probability that one edge scores higher than another is just 1/2 (by symmetry). Thus the rank of an edge should be distributed as a binomial of parameters (#entities, 1/2), plus one because ranks start at 1. The MRR is the mean reciprocal rank, so instead we'll calculate the expected reciprocal rank, which is the expected value of `1 / 1 + B(N, 1/2)`. [According to Wolfram Alpha](https://www.wolframalpha.com/input/?i=sum_%7Bn%3D0%7D%5EN+1%2F%281%2Bn%29+Binomial%5BN%2Cn%5D+1%2F%282%5EN%29) this is `2/(1 + N) - 2^(-N)/(1 + N)` (this makes sense, as the first term is what we'd expect from a rough estimate, since it's the inverse of the average rank). So you can plug in your value of N there and see what you get.

(If I remember correctly, however, the way we compute the MRR in PBG is a bit of an approximation when you're not using all_negs, because in that case we only compute the rank among the negatives, which are fewer than all the entities, so the rank will appear to be better. I'd say that to account for this you can replace the `N` above with the number of negatives in your config).

**Comment by adamlerer** [comment]
If you really want to look at the performance of an untrained PBG model, just run for one epoch with `lr=0`.
