### ISSUE TITLE
Why `background_io` is set to False by default?

### ISSUE THREAD

**Issue by zijwang** [facebookresearch/PyTorch-BigGraph#90]
Is there any specific consideration why `background_io` in the configuration schema is set to False by default?

**Comment by lerks** [comment]
I'm not sure but my guess is because of backwards compatibility (i.e., it is a feature that was introduced at a later point and in order to have the previous configs keep working in the same way it had to be disabled by default).

You might argue that background I/O does not introduce any functional difference, and that thus noone would have noticed if it had been turned on unexpectedly under their feet. However, it does has some averse effects, for example it causes PBG to consume up to twice the memory (the one it needs now plus the one it needs at the next pass). Since usually PBG's bottleneck is memory, people may have tuned their configs to work close to the limit and a sudden unexpected increase might have killed their experiments.
