### ISSUE TITLE
How to sample negative triples in PBG.

### ISSUE THREAD

**Issue by JessicaAlphy** [facebookresearch/PyTorch-BigGraph#95]
## Steps to reproduce

 I am a reader of your significant research paperwork named "PyTorch-Biggraph: a large-scale graph embedding system". Could I ask you several questions?
      1.  Could you please explain the "Batched Negative Sampling strategy", which PBG adopted a bit more detailed for me? So sorry to waste your precious time. Looking forward to your reply. 
     2.  Section 4.2--distributed execution, there are two servers across the N training machine, one is the  Sharded Parameter Server, the other is the sharded Partition Server,  the paper says that a bucket of edges loaded from shared disk. And for the relation parameters, they are stored in the sharded partition server. So my question is what is the difference between a bucket of edges and relation parameters, are they the same things? Because in my view, relation is equals to edegs. So Could you give me an example to illustrate the difference?
   Looking forward to your reply.
                                                                                                                                Best regards
                                                                                                                          Jessica Cheshire

**Comment by lerks** [comment]
1. PBG processes edges in batches. What this means is that it processes the input data (i.e., the list of edges) piece by piece, and these pieces we call batches. Each batch is typically 1000 edges, although this is configurable. While training on this batch, it gets split further into chunks, which could consist of 50 edges (again configurable). When we need to sample negative edges for a given positive edge, we do so by "corrupting" the positive, i.e., replacing one of its endpoints with another entity. The entities we choose to perform this corruption are obtained in two ways: some are uniformly sampled across all entities, **the others are all the other entities in the same batch as the positive edge**.
  This is all there is to it: batched negative sampling means that negatives are "sourced" (also) from the batch, not just uniformly.
2. I guess the wording in that passage used an abbreviation that made it confusing: when we talk about "relation parameters" we typically mean "relation **types** parameters". If you consider a knowledge base graph, each edge has a type (`was_born_in`, `lived_in`, `died_in`, ...). Since there could be multiple edges, of different types, between the same pair of entities, we need to be able to modify the score of an edge based on its type. The way this is done is that for each type of edge there is an operator that transforms the embedding of the right-hand side entity before it is compared with the left-hand side one. These operators can be of several types (we have a few built-in: translation, linear, complex multiplication, ...) and they can have parameters that are trained alongside the embeddings: these are the relation type parameters.
  Just to stress it once more: while each edge is a distinct triple of (source, type, target) identifiers, the relation type parameters are a set of (floating-point) values which, in a sense, are "common" to all the edges of that type.
  (PS: the relation type parameters are stored in the sharded _parameter_ server, not the partition server)

**Comment by lerks** [comment]
Closing as there's been no follow-up in three weeks. Please reopen if needed.
